# Generated by Django 3.2.6 on 2021-10-17 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0002_allblog'),
    ]

    operations = [
        migrations.AddField(
            model_name='allblog',
            name='slug',
            field=models.CharField(default='', max_length=100),
        ),
    ]
